name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    steps:
      - name: Install unzip
        run: apt-get update && apt-get install -y unzip
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Playwright tests
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          bun x playwright test --workers=4
      - name: Upload HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
